var project_def_tests = [
    // === id_project - SEARCH (PK autoincrement) ===
    ["project", "id_project", "input", 1, "Validar max_size id en SEARCH", "SEARCH", "id_project_max_size_KO", "ID supera tamano maximo"],
    ["project", "id_project", "input", 2, "Validar format id en SEARCH", "SEARCH", "id_project_format_KO", "ID con formato incorrecto"],
    ["project", "id_project", "input", 3, "Validar id correcto en SEARCH", "SEARCH", true, "ID correcto"],

    // === name_project - ADD ===
    ["project", "name_project", "input", 4, "Validar min_size name en ADD (min 15)", "ADD", "name_project_min_size_KO", "Nombre demasiado corto"],
    ["project", "name_project", "input", 5, "Validar max_size name en ADD", "ADD", "name_project_max_size_KO", "Nombre demasiado largo"],
    ["project", "name_project", "input", 6, "Validar format name en ADD", "ADD", "name_project_format_KO", "Nombre con caracteres invalidos"],
    ["project", "name_project", "input", 7, "Validar name correcto en ADD", "ADD", true, "Nombre correcto"],

    // === name_project - EDIT ===
    ["project", "name_project", "input", 8, "Validar min_size name en EDIT", "EDIT", "name_project_min_size_KO", "Nombre demasiado corto en EDIT"],
    ["project", "name_project", "input", 9, "Validar max_size name en EDIT", "EDIT", "name_project_max_size_KO", "Nombre demasiado largo en EDIT"],
    ["project", "name_project", "input", 10, "Validar format name en EDIT", "EDIT", "name_project_format_KO", "Nombre con caracteres invalidos en EDIT"],
    ["project", "name_project", "input", 11, "Validar name correcto en EDIT", "EDIT", true, "Nombre correcto en EDIT"],

    // === name_project - SEARCH ===
    ["project", "name_project", "input", 12, "Validar max_size name en SEARCH", "SEARCH", "name_project_max_size_KO", "Nombre demasiado largo en SEARCH"],
    ["project", "name_project", "input", 13, "Validar format name en SEARCH", "SEARCH", "name_project_format_KO", "Nombre con caracteres invalidos en SEARCH"],
    ["project", "name_project", "input", 14, "Validar name correcto en SEARCH", "SEARCH", true, "Nombre correcto en SEARCH"],

    // === start_date_project - ADD ===
    ["project", "start_date_project", "input", 15, "Validar date fecha inicio en ADD", "ADD", "start_date_project_date_KO", "Formato de fecha incorrecto"],
    ["project", "start_date_project", "input", 16, "Validar fecha inicio correcta en ADD", "ADD", true, "Fecha inicio correcta"],

    // === start_date_project - EDIT ===
    ["project", "start_date_project", "input", 17, "Validar date fecha inicio en EDIT", "EDIT", "start_date_project_date_KO", "Formato de fecha incorrecto en EDIT"],
    ["project", "start_date_project", "input", 18, "Validar fecha inicio correcta en EDIT", "EDIT", true, "Fecha inicio correcta en EDIT"],

    // === start_date_project - SEARCH ===
    ["project", "start_date_project", "input", 19, "Validar format fecha inicio en SEARCH", "SEARCH", "start_date_project_format_KO", "Formato de fecha incorrecto en SEARCH"],
    ["project", "start_date_project", "input", 20, "Validar fecha inicio correcta en SEARCH", "SEARCH", true, "Fecha inicio correcta en SEARCH"],

    // === end_date_project - ADD ===
    ["project", "end_date_project", "input", 21, "Validar date fecha fin en ADD", "ADD", "end_date_project_date_KO", "Formato de fecha fin incorrecto"],
    ["project", "end_date_project", "input", 22, "Validar personalized end_date > start_date en ADD", "ADD", "end_date_project_personalized_KO", "Fecha fin anterior a fecha inicio"],
    ["project", "end_date_project", "input", 23, "Validar fecha fin correcta en ADD", "ADD", true, "Fecha fin correcta"],

    // === end_date_project - EDIT ===
    ["project", "end_date_project", "input", 24, "Validar date fecha fin en EDIT", "EDIT", "end_date_project_date_KO", "Formato de fecha fin incorrecto en EDIT"],
    ["project", "end_date_project", "input", 25, "Validar personalized end_date > start_date en EDIT", "EDIT", "end_date_project_personalized_KO", "Fecha fin anterior a fecha inicio en EDIT"],
    ["project", "end_date_project", "input", 26, "Validar fecha fin correcta en EDIT", "EDIT", true, "Fecha fin correcta en EDIT"],

    // === end_date_project - SEARCH ===
    ["project", "end_date_project", "input", 27, "Validar format fecha fin en SEARCH", "SEARCH", "end_date_project_format_KO", "Formato de fecha fin incorrecto en SEARCH"],
    ["project", "end_date_project", "input", 28, "Validar fecha fin correcta en SEARCH", "SEARCH", true, "Fecha fin correcta en SEARCH"],

    // === responsable_project - ADD ===
    ["project", "responsable_project", "input", 29, "Validar min_size responsable en ADD", "ADD", "responsable_project_min_size_KO", "Responsable demasiado corto"],
    ["project", "responsable_project", "input", 30, "Validar max_size responsable en ADD", "ADD", "responsable_project_max_size_KO", "Responsable demasiado largo"],
    ["project", "responsable_project", "input", 31, "Validar format responsable en ADD", "ADD", "responsable_project_format_KO", "Responsable con caracteres invalidos"],
    ["project", "responsable_project", "input", 32, "Validar responsable correcto en ADD", "ADD", true, "Responsable correcto"],

    // === responsable_project - EDIT ===
    ["project", "responsable_project", "input", 33, "Validar min_size responsable en EDIT", "EDIT", "responsable_project_min_size_KO", "Responsable demasiado corto en EDIT"],
    ["project", "responsable_project", "input", 34, "Validar max_size responsable en EDIT", "EDIT", "responsable_project_max_size_KO", "Responsable demasiado largo en EDIT"],
    ["project", "responsable_project", "input", 35, "Validar format responsable en EDIT", "EDIT", "responsable_project_format_KO", "Responsable con caracteres invalidos en EDIT"],
    ["project", "responsable_project", "input", 36, "Validar responsable correcto en EDIT", "EDIT", true, "Responsable correcto en EDIT"],

    // === responsable_project - SEARCH ===
    ["project", "responsable_project", "input", 37, "Validar max_size responsable en SEARCH", "SEARCH", "responsable_project_max_size_KO", "Responsable demasiado largo en SEARCH"],
    ["project", "responsable_project", "input", 38, "Validar format responsable en SEARCH", "SEARCH", "responsable_project_format_KO", "Responsable con caracteres invalidos en SEARCH"],
    ["project", "responsable_project", "input", 39, "Validar responsable correcto en SEARCH", "SEARCH", true, "Responsable correcto en SEARCH"],

    // === organization_project - ADD ===
    ["project", "organization_project", "input", 40, "Validar min_size organization en ADD", "ADD", "organization_project_min_size_KO", "Organizacion demasiado corta"],
    ["project", "organization_project", "input", 41, "Validar max_size organization en ADD", "ADD", "organization_project_max_size_KO", "Organizacion demasiado larga"],
    ["project", "organization_project", "input", 42, "Validar format organization en ADD", "ADD", "organization_project_format_KO", "Organizacion con caracteres invalidos"],
    ["project", "organization_project", "input", 43, "Validar organization correcta en ADD", "ADD", true, "Organizacion correcta"],

    // === organization_project - EDIT ===
    ["project", "organization_project", "input", 44, "Validar min_size organization en EDIT", "EDIT", "organization_project_min_size_KO", "Organizacion demasiado corta en EDIT"],
    ["project", "organization_project", "input", 45, "Validar max_size organization en EDIT", "EDIT", "organization_project_max_size_KO", "Organizacion demasiado larga en EDIT"],
    ["project", "organization_project", "input", 46, "Validar format organization en EDIT", "EDIT", "organization_project_format_KO", "Organizacion con caracteres invalidos en EDIT"],
    ["project", "organization_project", "input", 47, "Validar organization correcta en EDIT", "EDIT", true, "Organizacion correcta en EDIT"],

    // === organization_project - SEARCH ===
    ["project", "organization_project", "input", 48, "Validar max_size organization en SEARCH", "SEARCH", "organization_project_max_size_KO", "Organizacion demasiado larga en SEARCH"],
    ["project", "organization_project", "input", 49, "Validar format organization en SEARCH", "SEARCH", "organization_project_format_KO", "Organizacion con caracteres invalidos en SEARCH"],
    ["project", "organization_project", "input", 50, "Validar organization correcta en SEARCH", "SEARCH", true, "Organizacion correcta en SEARCH"],

    // === description_project - ADD ===
    ["project", "description_project", "textarea", 51, "Validar min_size description en ADD (min 30)", "ADD", "description_project_min_size_KO", "Descripcion demasiado corta"],
    ["project", "description_project", "textarea", 52, "Validar max_size description en ADD", "ADD", "description_project_max_size_KO", "Descripcion demasiado larga"],
    ["project", "description_project", "textarea", 53, "Validar format description en ADD (solo ASCII)", "ADD", "description_project_format_KO", "Descripcion con caracteres no ASCII"],
    ["project", "description_project", "textarea", 54, "Validar description correcta en ADD", "ADD", true, "Descripcion correcta"],

    // === description_project - EDIT ===
    ["project", "description_project", "textarea", 55, "Validar min_size description en EDIT", "EDIT", "description_project_min_size_KO", "Descripcion demasiado corta en EDIT"],
    ["project", "description_project", "textarea", 56, "Validar max_size description en EDIT", "EDIT", "description_project_max_size_KO", "Descripcion demasiado larga en EDIT"],
    ["project", "description_project", "textarea", 57, "Validar format description en EDIT", "EDIT", "description_project_format_KO", "Descripcion con caracteres no ASCII en EDIT"],
    ["project", "description_project", "textarea", 58, "Validar description correcta en EDIT", "EDIT", true, "Descripcion correcta en EDIT"],

    // === description_project - SEARCH ===
    ["project", "description_project", "textarea", 59, "Validar max_size description en SEARCH", "SEARCH", "description_project_max_size_KO", "Descripcion demasiado larga en SEARCH"],
    ["project", "description_project", "textarea", 60, "Validar format description en SEARCH", "SEARCH", "description_project_format_KO", "Descripcion con caracteres no ASCII en SEARCH"],
    ["project", "description_project", "textarea", 61, "Validar description correcta en SEARCH", "SEARCH", true, "Descripcion correcta en SEARCH"],

    // === file_project - ADD ===
    ["project", "file_project", "file", 62, "Validar no_file en ADD", "ADD", "file_project_no_file_KO", "Sin fichero"],
    ["project", "file_project", "file", 63, "Validar min_size nombre fichero en ADD", "ADD", "file_project_min_size_KO", "Nombre del fichero demasiado corto"],
    ["project", "file_project", "file", 64, "Validar max_size nombre fichero en ADD", "ADD", "file_project_max_size_KO", "Nombre del fichero demasiado largo"],
    ["project", "file_project", "file", 65, "Validar format_name_file en ADD", "ADD", "file_project_format_name_file_KO", "Nombre fichero incorrecto"],
    ["project", "file_project", "file", 66, "Validar type_file en ADD", "ADD", "file_project_type_file_KO", "Tipo fichero no permitido"],
    ["project", "file_project", "file", 67, "Validar max_size_file en ADD", "ADD", "file_project_max_size_file_KO", "Fichero demasiado grande"],
    ["project", "file_project", "file", 68, "Validar file correcto en ADD", "ADD", true, "Fichero correcto"],

    // === file_project - EDIT ===
    ["project", "file_project", "file", 69, "Validar min_size nombre fichero en EDIT", "EDIT", "file_project_min_size_KO", "Nombre del fichero demasiado corto en EDIT"],
    ["project", "file_project", "file", 70, "Validar max_size nombre fichero en EDIT", "EDIT", "file_project_max_size_KO", "Nombre del fichero demasiado largo en EDIT"],
    ["project", "file_project", "file", 71, "Validar format_name_file en EDIT", "EDIT", "file_project_format_name_file_KO", "Nombre fichero incorrecto en EDIT"],
    ["project", "file_project", "file", 72, "Validar type_file en EDIT", "EDIT", "file_project_type_file_KO", "Tipo fichero no permitido en EDIT"],
    ["project", "file_project", "file", 73, "Validar max_size_file en EDIT", "EDIT", "file_project_max_size_file_KO", "Fichero demasiado grande en EDIT"],
    ["project", "file_project", "file", 74, "Validar file correcto en EDIT", "EDIT", true, "Fichero correcto en EDIT"],

    // === file_project - SEARCH (modo texto) ===
    ["project", "file_project", "input", 75, "Validar max_size de file en SEARCH", "SEARCH", "file_project_max_size_KO", "Nombre del fichero demasiado largo en SEARCH"],
    ["project", "file_project", "input", 76, "Validar format de file en SEARCH", "SEARCH", "file_project_format_KO", "Formato incorrecto en busqueda"],
    ["project", "file_project", "input", 77, "Validar file correcto en SEARCH", "SEARCH", true, "Busqueda de fichero correcta"],

    // === code_project - ADD ===
    ["project", "code_project", "input", 78, "Validar min_size code en ADD", "ADD", "code_project_min_size_KO", "Codigo demasiado corto"],
    ["project", "code_project", "input", 79, "Validar max_size code en ADD", "ADD", "code_project_max_size_KO", "Codigo demasiado largo"],
    ["project", "code_project", "input", 80, "Validar format code en ADD", "ADD", "code_project_format_KO", "Codigo con caracteres invalidos"],
    ["project", "code_project", "input", 81, "Validar code correcto en ADD", "ADD", true, "Codigo correcto"],

    // === code_project - EDIT ===
    ["project", "code_project", "input", 82, "Validar min_size code en EDIT", "EDIT", "code_project_min_size_KO", "Codigo demasiado corto en EDIT"],
    ["project", "code_project", "input", 83, "Validar max_size code en EDIT", "EDIT", "code_project_max_size_KO", "Codigo demasiado largo en EDIT"],
    ["project", "code_project", "input", 84, "Validar format code en EDIT", "EDIT", "code_project_format_KO", "Codigo con caracteres invalidos en EDIT"],
    ["project", "code_project", "input", 85, "Validar code correcto en EDIT", "EDIT", true, "Codigo correcto en EDIT"],

    // === code_project - SEARCH ===
    ["project", "code_project", "input", 86, "Validar max_size code en SEARCH", "SEARCH", "code_project_max_size_KO", "Codigo demasiado largo en SEARCH"],
    ["project", "code_project", "input", 87, "Validar format code en SEARCH", "SEARCH", "code_project_format_KO", "Codigo con caracteres invalidos en SEARCH"],
    ["project", "code_project", "input", 88, "Validar code correcto en SEARCH", "SEARCH", true, "Codigo correcto en SEARCH"],

    // === acronym_project - ADD ===
    ["project", "acronym_project", "input", 89, "Validar min_size acronym en ADD", "ADD", "acronym_project_min_size_KO", "Acronimo demasiado corto"],
    ["project", "acronym_project", "input", 90, "Validar max_size acronym en ADD", "ADD", "acronym_project_max_size_KO", "Acronimo demasiado largo"],
    ["project", "acronym_project", "input", 91, "Validar format acronym en ADD (sin espacios)", "ADD", "acronym_project_format_KO", "Acronimo con formato incorrecto"],
    ["project", "acronym_project", "input", 92, "Validar acronym correcto en ADD", "ADD", true, "Acronimo correcto"],

    // === acronym_project - EDIT ===
    ["project", "acronym_project", "input", 93, "Validar min_size acronym en EDIT", "EDIT", "acronym_project_min_size_KO", "Acronimo demasiado corto en EDIT"],
    ["project", "acronym_project", "input", 94, "Validar max_size acronym en EDIT", "EDIT", "acronym_project_max_size_KO", "Acronimo demasiado largo en EDIT"],
    ["project", "acronym_project", "input", 95, "Validar format acronym en EDIT", "EDIT", "acronym_project_format_KO", "Acronimo con formato incorrecto en EDIT"],
    ["project", "acronym_project", "input", 96, "Validar acronym correcto en EDIT", "EDIT", true, "Acronimo correcto en EDIT"],

    // === acronym_project - SEARCH ===
    ["project", "acronym_project", "input", 97, "Validar max_size acronym en SEARCH", "SEARCH", "acronym_project_max_size_KO", "Acronimo demasiado largo en SEARCH"],
    ["project", "acronym_project", "input", 98, "Validar format acronym en SEARCH", "SEARCH", "acronym_project_format_KO", "Acronimo con formato incorrecto en SEARCH"],
    ["project", "acronym_project", "input", 99, "Validar acronym correcto en SEARCH", "SEARCH", true, "Acronimo correcto en SEARCH"],

    // === id_sampling_methodology - ADD ===
    ["project", "id_sampling_methodology", "input", 100, "Validar min_size id_sampling en ADD", "ADD", "id_sampling_methodology_min_size_KO", "ID metodologia demasiado corto"],
    ["project", "id_sampling_methodology", "input", 101, "Validar max_size id_sampling en ADD", "ADD", "id_sampling_methodology_max_size_KO", "ID metodologia demasiado largo"],
    ["project", "id_sampling_methodology", "input", 102, "Validar format id_sampling en ADD", "ADD", "id_sampling_methodology_format_KO", "ID metodologia con formato incorrecto"],
    ["project", "id_sampling_methodology", "input", 103, "Validar id_sampling correcto en ADD", "ADD", true, "ID metodologia correcto"],

    // === id_sampling_methodology - EDIT ===
    ["project", "id_sampling_methodology", "input", 104, "Validar min_size id_sampling en EDIT", "EDIT", "id_sampling_methodology_min_size_KO", "ID metodologia demasiado corto en EDIT"],
    ["project", "id_sampling_methodology", "input", 105, "Validar max_size id_sampling en EDIT", "EDIT", "id_sampling_methodology_max_size_KO", "ID metodologia demasiado largo en EDIT"],
    ["project", "id_sampling_methodology", "input", 106, "Validar format id_sampling en EDIT", "EDIT", "id_sampling_methodology_format_KO", "ID metodologia con formato incorrecto en EDIT"],
    ["project", "id_sampling_methodology", "input", 107, "Validar id_sampling correcto en EDIT", "EDIT", true, "ID metodologia correcto en EDIT"],

    // === id_sampling_methodology - SEARCH ===
    ["project", "id_sampling_methodology", "input", 108, "Validar max_size id_sampling en SEARCH", "SEARCH", "id_sampling_methodology_max_size_KO", "ID metodologia demasiado largo en SEARCH"],
    ["project", "id_sampling_methodology", "input", 109, "Validar format id_sampling en SEARCH", "SEARCH", "id_sampling_methodology_format_KO", "ID metodologia con formato incorrecto en SEARCH"],
    ["project", "id_sampling_methodology", "input", 110, "Validar id_sampling correcto en SEARCH", "SEARCH", true, "ID metodologia correcto en SEARCH"],

    // === fechas - validacion de fecha real (atomica date) ===
    // (la validacion atomica date comprueba que la fecha exista en el
    //  calendario, no solo que cumpla el patron dd/mm/aaaa)
    ["project", "start_date_project", "input", 111, "Validar date fecha real start_date en ADD (ej. 31/02/2024)", "ADD", "start_date_project_date_KO", "Fecha de inicio inexistente en el calendario"],
    ["project", "start_date_project", "input", 112, "Validar date fecha real start_date en EDIT", "EDIT", "start_date_project_date_KO", "Fecha de inicio inexistente en el calendario EDIT"],
    ["project", "end_date_project", "input", 113, "Validar date fecha real end_date en ADD (ej. 30/02/2024)", "ADD", "end_date_project_date_KO", "Fecha de fin inexistente en el calendario"],
    ["project", "end_date_project", "input", 114, "Validar date fecha real end_date en EDIT", "EDIT", "end_date_project_date_KO", "Fecha de fin inexistente en el calendario EDIT"],

    // === Ampliacion caja negra: valores limite, clases invalidas adicionales, MIME y calendario ===
    ["project", "id_project", "input", 115, "Validar id en limite exacto de max_size (11 digitos) en SEARCH", "SEARCH", true, "ID en el limite maximo permitido"],
    ["project", "name_project", "input", 116, "Validar name en limite exacto de min_size (15) en ADD", "ADD", true, "Nombre en el limite minimo permitido"],
    ["project", "name_project", "input", 117, "Validar name en limite exacto de max_size (100) en ADD", "ADD", true, "Nombre en el limite maximo permitido"],
    ["project", "name_project", "input", 118, "Validar name con simbolos no permitidos en ADD", "ADD", "name_project_format_KO", "Nombre con simbolos especiales"],
    ["project", "responsable_project", "input", 119, "Validar responsable en limite exacto de min_size (6) en ADD", "ADD", true, "Responsable en el limite minimo permitido"],
    ["project", "responsable_project", "input", 120, "Validar responsable en limite exacto de max_size (60) en ADD", "ADD", true, "Responsable en el limite maximo permitido"],
    ["project", "responsable_project", "input", 121, "Validar responsable con simbolos no permitidos en ADD", "ADD", "responsable_project_format_KO", "Responsable con simbolos especiales"],
    ["project", "organization_project", "input", 122, "Validar organization en limite exacto de min_size (6) en ADD", "ADD", true, "Organizacion en el limite minimo permitido"],
    ["project", "organization_project", "input", 123, "Validar organization en limite exacto de max_size (100) en ADD", "ADD", true, "Organizacion en el limite maximo permitido"],
    ["project", "organization_project", "input", 124, "Validar organization con simbolos no permitidos en ADD", "ADD", "organization_project_format_KO", "Organizacion con simbolos especiales"],
    ["project", "description_project", "textarea", 125, "Validar description en limite exacto de min_size (30) en ADD", "ADD", true, "Descripcion en el limite minimo permitido"],
    ["project", "description_project", "textarea", 126, "Validar description en limite exacto de max_size (500) en ADD", "ADD", true, "Descripcion en el limite maximo permitido"],
    ["project", "code_project", "input", 127, "Validar code en limite exacto de min_size (6) en ADD", "ADD", true, "Codigo en el limite minimo permitido"],
    ["project", "code_project", "input", 128, "Validar code en limite exacto de max_size (50) en ADD", "ADD", true, "Codigo en el limite maximo permitido"],
    ["project", "code_project", "input", 129, "Validar code con digitos no permitidos en ADD", "ADD", "code_project_format_KO", "Codigo con digitos"],
    ["project", "acronym_project", "input", 130, "Validar acronym en limite exacto de min_size (6) en ADD", "ADD", true, "Acronimo en el limite minimo permitido"],
    ["project", "acronym_project", "input", 131, "Validar acronym en limite exacto de max_size (15) en ADD", "ADD", true, "Acronimo en el limite maximo permitido"],
    ["project", "id_sampling_methodology", "input", 132, "Validar id_sampling en limite exacto de min_size (1) en ADD", "ADD", true, "ID metodologia en el limite minimo permitido"],
    ["project", "id_sampling_methodology", "input", 133, "Validar id_sampling en limite exacto de max_size (11) en ADD", "ADD", true, "ID metodologia en el limite maximo permitido"],
    ["project", "file_project", "file", 134, "Validar file con tipo MIME doc en ADD", "ADD", true, "Fichero .doc valido"],
    ["project", "file_project", "file", 135, "Validar file con tipo MIME docx en ADD", "ADD", true, "Fichero .docx valido"],
    ["project", "file_project", "file", 136, "Validar file justo por debajo del limite de max_size_file (1999999 bytes, menor de 2000000) en ADD", "ADD", true, "Fichero por debajo del limite de tamano (valido)"],
    ["project", "file_project", "file", 137, "Validar file en limite exacto de min_size del nombre (7) en ADD", "ADD", true, "Nombre de fichero en el limite minimo"],
    ["project", "file_project", "file", 138, "Validar file en limite exacto de max_size del nombre (100) en ADD", "ADD", true, "Nombre de fichero en el limite maximo"],
    ["project", "end_date_project", "input", 139, "Validar fecha fin real en ano bisiesto (29/02/2024) en ADD", "ADD", true, "Fecha fin valida en ano bisiesto"]
];

var project_pruebas = [
    ["project", "id_project", 1, 1, "SEARCH", {"id_project": "123456789012"}, "id_project_max_size_KO"],
    ["project", "id_project", 1, 2, "SEARCH", {"id_project": "99"}, true],
    ["project", "id_project", 2, 3, "SEARCH", {"id_project": "abc"}, "id_project_format_KO"],
    ["project", "id_project", 2, 4, "SEARCH", {"id_project": "99"}, true],
    ["project", "id_project", 3, 5, "SEARCH", {"id_project": "999"}, true],
    ["project", "id_project", 3, 6, "SEARCH", {"id_project": "abc"}, "id_project_format_KO"],
    ["project", "name_project", 4, 7, "ADD", {"name_project": "Short Name"}, "name_project_min_size_KO"],
    ["project", "name_project", 4, 8, "ADD", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 5, 9, "ADD", {"name_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "name_project_max_size_KO"],
    ["project", "name_project", 5, 10, "ADD", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 6, 11, "ADD", {"name_project": "Project Name With 123"}, "name_project_format_KO"],
    ["project", "name_project", 6, 12, "ADD", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 7, 13, "ADD", {"name_project": "Valid Project Name For Testing"}, true],
    ["project", "name_project", 7, 14, "ADD", {"name_project": ""}, "name_project_min_size_KO"],
    ["project", "name_project", 8, 15, "EDIT", {"name_project": "Short Edit"}, "name_project_min_size_KO"],
    ["project", "name_project", 8, 16, "EDIT", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 9, 17, "EDIT", {"name_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "name_project_max_size_KO"],
    ["project", "name_project", 9, 18, "EDIT", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 10, 19, "EDIT", {"name_project": "Project Name Edited 99"}, "name_project_format_KO"],
    ["project", "name_project", 10, 20, "EDIT", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 11, 21, "EDIT", {"name_project": "Edited Valid Project Name"}, true],
    ["project", "name_project", 11, 22, "EDIT", {"name_project": ""}, "name_project_min_size_KO"],
    ["project", "name_project", 12, 23, "SEARCH", {"name_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "name_project_max_size_KO"],
    ["project", "name_project", 12, 24, "SEARCH", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 13, 25, "SEARCH", {"name_project": "Search Name 1"}, "name_project_format_KO"],
    ["project", "name_project", 13, 26, "SEARCH", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "name_project", 14, 27, "SEARCH", {"name_project": "Search Project"}, true],
    ["project", "name_project", 14, 28, "SEARCH", {"name_project": "9ñ@!9ñ@!9ñ@!"}, "name_project_format_KO"],
    ["project", "start_date_project", 15, 29, "ADD", {"start_date_project": "2024-01-15"}, "start_date_project_date_KO"],
    ["project", "start_date_project", 15, 30, "ADD", {"start_date_project": "15/01/2024"}, true],
    ["project", "start_date_project", 16, 31, "ADD", {"start_date_project": "15/01/2024"}, true],
    ["project", "start_date_project", 16, 32, "ADD", {"start_date_project": "wrong-date"}, "start_date_project_date_KO"],
    ["project", "start_date_project", 17, 33, "EDIT", {"start_date_project": "2024-01-15"}, "start_date_project_date_KO"],
    ["project", "start_date_project", 17, 34, "EDIT", {"start_date_project": "15/01/2024"}, true],
    ["project", "start_date_project", 18, 35, "EDIT", {"start_date_project": "01/01/2024"}, true],
    ["project", "start_date_project", 18, 36, "EDIT", {"start_date_project": "wrong-date"}, "start_date_project_date_KO"],
    ["project", "start_date_project", 19, 37, "SEARCH", {"start_date_project": "wrong-date"}, "start_date_project_format_KO"],
    ["project", "start_date_project", 19, 38, "SEARCH", {"start_date_project": "15/01/2024"}, true],
    ["project", "start_date_project", 20, 39, "SEARCH", {"start_date_project": "01/01/2024"}, true],
    ["project", "start_date_project", 20, 40, "SEARCH", {"start_date_project": "wrong-date"}, "start_date_project_format_KO"],
    ["project", "end_date_project", 21, 41, "ADD", {"end_date_project": "2024-12-31"}, "end_date_project_date_KO"],
    ["project", "end_date_project", 21, 42, "ADD", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 22, 43, "ADD", {"end_date_project": "01/01/2023", "start_date_project": "15/06/2024"}, "end_date_project_personalized_KO"],
    ["project", "end_date_project", 22, 44, "ADD", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 23, 45, "ADD", {"end_date_project": "31/12/2025", "start_date_project": "01/01/2024"}, true],
    ["project", "end_date_project", 23, 46, "ADD", {"end_date_project": "wrong-date"}, "end_date_project_date_KO"],
    ["project", "end_date_project", 24, 47, "EDIT", {"end_date_project": "2024-12-31"}, "end_date_project_date_KO"],
    ["project", "end_date_project", 24, 48, "EDIT", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 25, 49, "EDIT", {"end_date_project": "01/01/2023", "start_date_project": "15/06/2024"}, "end_date_project_personalized_KO"],
    ["project", "end_date_project", 25, 50, "EDIT", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 26, 51, "EDIT", {"end_date_project": "31/12/2026", "start_date_project": "01/01/2024"}, true],
    ["project", "end_date_project", 26, 52, "EDIT", {"end_date_project": "wrong-date"}, "end_date_project_date_KO"],
    ["project", "end_date_project", 27, 53, "SEARCH", {"end_date_project": "wrong-date"}, "end_date_project_format_KO"],
    ["project", "end_date_project", 27, 54, "SEARCH", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 28, 55, "SEARCH", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 28, 56, "SEARCH", {"end_date_project": "wrong-date"}, "end_date_project_format_KO"],
    ["project", "responsable_project", 29, 57, "ADD", {"responsable_project": "Abc"}, "responsable_project_min_size_KO"],
    ["project", "responsable_project", 29, 58, "ADD", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 30, 59, "ADD", {"responsable_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "responsable_project_max_size_KO"],
    ["project", "responsable_project", 30, 60, "ADD", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 31, 61, "ADD", {"responsable_project": "Juan 123"}, "responsable_project_format_KO"],
    ["project", "responsable_project", 31, 62, "ADD", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 32, 63, "ADD", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 32, 64, "ADD", {"responsable_project": ""}, "responsable_project_min_size_KO"],
    ["project", "responsable_project", 33, 65, "EDIT", {"responsable_project": "Abc"}, "responsable_project_min_size_KO"],
    ["project", "responsable_project", 33, 66, "EDIT", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 34, 67, "EDIT", {"responsable_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "responsable_project_max_size_KO"],
    ["project", "responsable_project", 34, 68, "EDIT", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 35, 69, "EDIT", {"responsable_project": "Maria 456"}, "responsable_project_format_KO"],
    ["project", "responsable_project", 35, 70, "EDIT", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 36, 71, "EDIT", {"responsable_project": "Maria Fernandez"}, true],
    ["project", "responsable_project", 36, 72, "EDIT", {"responsable_project": ""}, "responsable_project_min_size_KO"],
    ["project", "responsable_project", 37, 73, "SEARCH", {"responsable_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "responsable_project_max_size_KO"],
    ["project", "responsable_project", 37, 74, "SEARCH", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 38, 75, "SEARCH", {"responsable_project": "Buscar 1"}, "responsable_project_format_KO"],
    ["project", "responsable_project", 38, 76, "SEARCH", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "responsable_project", 39, 77, "SEARCH", {"responsable_project": "Juan"}, true],
    ["project", "responsable_project", 39, 78, "SEARCH", {"responsable_project": "9ñ@!9ñ@!9ñ@!"}, "responsable_project_format_KO"],
    ["project", "organization_project", 40, 79, "ADD", {"organization_project": "Abc"}, "organization_project_min_size_KO"],
    ["project", "organization_project", 40, 80, "ADD", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 41, 81, "ADD", {"organization_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "organization_project_max_size_KO"],
    ["project", "organization_project", 41, 82, "ADD", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 42, 83, "ADD", {"organization_project": "Org 123"}, "organization_project_format_KO"],
    ["project", "organization_project", 42, 84, "ADD", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 43, 85, "ADD", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 43, 86, "ADD", {"organization_project": ""}, "organization_project_min_size_KO"],
    ["project", "organization_project", 44, 87, "EDIT", {"organization_project": "Abc"}, "organization_project_min_size_KO"],
    ["project", "organization_project", 44, 88, "EDIT", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 45, 89, "EDIT", {"organization_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "organization_project_max_size_KO"],
    ["project", "organization_project", 45, 90, "EDIT", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 46, 91, "EDIT", {"organization_project": "Centro 99"}, "organization_project_format_KO"],
    ["project", "organization_project", 46, 92, "EDIT", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 47, 93, "EDIT", {"organization_project": "CSIC Espana"}, true],
    ["project", "organization_project", 47, 94, "EDIT", {"organization_project": ""}, "organization_project_min_size_KO"],
    ["project", "organization_project", 48, 95, "SEARCH", {"organization_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "organization_project_max_size_KO"],
    ["project", "organization_project", 48, 96, "SEARCH", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 49, 97, "SEARCH", {"organization_project": "Org 1"}, "organization_project_format_KO"],
    ["project", "organization_project", 49, 98, "SEARCH", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "organization_project", 50, 99, "SEARCH", {"organization_project": "Universidad"}, true],
    ["project", "organization_project", 50, 100, "SEARCH", {"organization_project": "9ñ@!9ñ@!9ñ@!"}, "organization_project_format_KO"],
    ["project", "description_project", 51, 101, "ADD", {"description_project": "Corto texto"}, "description_project_min_size_KO"],
    ["project", "description_project", 51, 102, "ADD", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 52, 103, "ADD", {"description_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "description_project_max_size_KO"],
    ["project", "description_project", 52, 104, "ADD", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 53, 105, "ADD", {"description_project": "Esta descripcion contiene caracteres ñ no ASCII para fallar el formato"}, "description_project_format_KO"],
    ["project", "description_project", 53, 106, "ADD", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 54, 107, "ADD", {"description_project": "This project involves a comprehensive study of soil characteristics and their impact"}, true],
    ["project", "description_project", 54, 108, "ADD", {"description_project": ""}, "description_project_min_size_KO"],
    ["project", "description_project", 55, 109, "EDIT", {"description_project": "Corto"}, "description_project_min_size_KO"],
    ["project", "description_project", 55, 110, "EDIT", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 56, 111, "EDIT", {"description_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "description_project_max_size_KO"],
    ["project", "description_project", 56, 112, "EDIT", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 57, 113, "EDIT", {"description_project": "Descripcion editada con caracter ñ que rompe formato ASCII imprimible"}, "description_project_format_KO"],
    ["project", "description_project", 57, 114, "EDIT", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 58, 115, "EDIT", {"description_project": "Updated description for this project which is long enough for validation purposes"}, true],
    ["project", "description_project", 58, 116, "EDIT", {"description_project": ""}, "description_project_min_size_KO"],
    ["project", "description_project", 59, 117, "SEARCH", {"description_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "description_project_max_size_KO"],
    ["project", "description_project", 59, 118, "SEARCH", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 60, 119, "SEARCH", {"description_project": "Search ñ no ASCII"}, "description_project_format_KO"],
    ["project", "description_project", 60, 120, "SEARCH", {"description_project": "This is a valid project description with enough characters for minimum length"}, true],
    ["project", "description_project", 61, 121, "SEARCH", {"description_project": "Search description"}, true],
    ["project", "description_project", 61, 122, "SEARCH", {"description_project": "9ñ@!9ñ@!9ñ@!"}, "description_project_format_KO"],
    ["project", "file_project", 62, 123, "ADD", {"file_project": ""}, "file_project_no_file_KO"],
    ["project", "file_project", 62, 124, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 63, 125, "ADD", {"file_project": {"name": "ab.pdf", "type": "application/pdf", "size": 1000}}, "file_project_min_size_KO"],
    ["project", "file_project", 63, 126, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 64, 127, "ADD", {"file_project": {"name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf", "type": "application/pdf", "size": 1000}}, "file_project_max_size_KO"],
    ["project", "file_project", 64, 128, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 65, 129, "ADD", {"file_project": {"name": "mi archivo.pdf", "type": "application/pdf", "size": 5000}}, "file_project_format_name_file_KO"],
    ["project", "file_project", 65, 130, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 66, 131, "ADD", {"file_project": {"name": "imagen.png", "type": "image/png", "size": 5000}}, "file_project_type_file_KO"],
    ["project", "file_project", 66, 132, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 67, 133, "ADD", {"file_project": {"name": "archivogrande.pdf", "type": "application/pdf", "size": 3000000}}, "file_project_max_size_file_KO"],
    ["project", "file_project", 67, 134, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 68, 135, "ADD", {"file_project": {"name": "project.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 68, 136, "ADD", {"file_project": ""}, "file_project_no_file_KO"],
    ["project", "file_project", 69, 137, "EDIT", {"file_project": {"name": "ab.pdf", "type": "application/pdf", "size": 1000}}, "file_project_min_size_KO"],
    ["project", "file_project", 69, 138, "EDIT", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 70, 139, "EDIT", {"file_project": {"name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf", "type": "application/pdf", "size": 1000}}, "file_project_max_size_KO"],
    ["project", "file_project", 70, 140, "EDIT", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 71, 141, "EDIT", {"file_project": {"name": "mi archivo.pdf", "type": "application/pdf", "size": 5000}}, "file_project_format_name_file_KO"],
    ["project", "file_project", 71, 142, "EDIT", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 72, 143, "EDIT", {"file_project": {"name": "imagen.png", "type": "image/png", "size": 5000}}, "file_project_type_file_KO"],
    ["project", "file_project", 72, 144, "EDIT", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 73, 145, "EDIT", {"file_project": {"name": "archivogrande.pdf", "type": "application/pdf", "size": 3000000}}, "file_project_max_size_file_KO"],
    ["project", "file_project", 73, 146, "EDIT", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 100000}}, true],
    ["project", "file_project", 74, 147, "EDIT", {"file_project": {"name": "editado.docx", "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "size": 200000}}, true],
    ["project", "file_project", 74, 148, "EDIT", {"file_project": ""}, "file_project_min_size_KO"],
    ["project", "file_project", 75, 149, "SEARCH", {"file_project": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}, "file_project_max_size_KO"],
    ["project", "file_project", 75, 150, "SEARCH", {"file_project": "proyecto.pdf"}, true],
    ["project", "file_project", 76, 151, "SEARCH", {"file_project": "archivo 123.pdf"}, "file_project_format_KO"],
    ["project", "file_project", 76, 152, "SEARCH", {"file_project": "proyecto.pdf"}, true],
    ["project", "file_project", 77, 153, "SEARCH", {"file_project": "project.pdf"}, true],
    ["project", "file_project", 77, 154, "SEARCH", {"file_project": "archivo 1.pdf"}, "file_project_format_KO"],
    ["project", "code_project", 78, 155, "ADD", {"code_project": "AB"}, "code_project_min_size_KO"],
    ["project", "code_project", 78, 156, "ADD", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 79, 157, "ADD", {"code_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "code_project_max_size_KO"],
    ["project", "code_project", 79, 158, "ADD", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 80, 159, "ADD", {"code_project": "Codigo123"}, "code_project_format_KO"],
    ["project", "code_project", 80, 160, "ADD", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 81, 161, "ADD", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 81, 162, "ADD", {"code_project": ""}, "code_project_min_size_KO"],
    ["project", "code_project", 82, 163, "EDIT", {"code_project": "AB"}, "code_project_min_size_KO"],
    ["project", "code_project", 82, 164, "EDIT", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 83, 165, "EDIT", {"code_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "code_project_max_size_KO"],
    ["project", "code_project", 83, 166, "EDIT", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 84, 167, "EDIT", {"code_project": "Codigo99"}, "code_project_format_KO"],
    ["project", "code_project", 84, 168, "EDIT", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 85, 169, "EDIT", {"code_project": "Codigo Editado"}, true],
    ["project", "code_project", 85, 170, "EDIT", {"code_project": ""}, "code_project_min_size_KO"],
    ["project", "code_project", 86, 171, "SEARCH", {"code_project": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "code_project_max_size_KO"],
    ["project", "code_project", 86, 172, "SEARCH", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 87, 173, "SEARCH", {"code_project": "Codigo1"}, "code_project_format_KO"],
    ["project", "code_project", 87, 174, "SEARCH", {"code_project": "Codigo Proyecto"}, true],
    ["project", "code_project", 88, 175, "SEARCH", {"code_project": "Codigo"}, true],
    ["project", "code_project", 88, 176, "SEARCH", {"code_project": "9ñ@!9ñ@!9ñ@!"}, "code_project_format_KO"],
    ["project", "acronym_project", 89, 177, "ADD", {"acronym_project": "AB"}, "acronym_project_min_size_KO"],
    ["project", "acronym_project", 89, 178, "ADD", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 90, 179, "ADD", {"acronym_project": "AAAAAAAAAAAAAAAA"}, "acronym_project_max_size_KO"],
    ["project", "acronym_project", 90, 180, "ADD", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 91, 181, "ADD", {"acronym_project": "ACR CON ESP"}, "acronym_project_format_KO"],
    ["project", "acronym_project", 91, 182, "ADD", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 92, 183, "ADD", {"acronym_project": "PROYÑ.!"}, true],
    ["project", "acronym_project", 92, 184, "ADD", {"acronym_project": ""}, "acronym_project_min_size_KO"],
    ["project", "acronym_project", 93, 185, "EDIT", {"acronym_project": "AB"}, "acronym_project_min_size_KO"],
    ["project", "acronym_project", 93, 186, "EDIT", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 94, 187, "EDIT", {"acronym_project": "AAAAAAAAAAAAAAAA"}, "acronym_project_max_size_KO"],
    ["project", "acronym_project", 94, 188, "EDIT", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 95, 189, "EDIT", {"acronym_project": "ED 1.!"}, "acronym_project_format_KO"],
    ["project", "acronym_project", 95, 190, "EDIT", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 96, 191, "EDIT", {"acronym_project": "EDIT.ñ!"}, true],
    ["project", "acronym_project", 96, 192, "EDIT", {"acronym_project": ""}, "acronym_project_min_size_KO"],
    ["project", "acronym_project", 97, 193, "SEARCH", {"acronym_project": "AAAAAAAAAAAAAAAA"}, "acronym_project_max_size_KO"],
    ["project", "acronym_project", 97, 194, "SEARCH", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 98, 195, "SEARCH", {"acronym_project": "ACR ESP"}, "acronym_project_format_KO"],
    ["project", "acronym_project", 98, 196, "SEARCH", {"acronym_project": "PROY.!"}, true],
    ["project", "acronym_project", 99, 197, "SEARCH", {"acronym_project": "PROY"}, true],
    ["project", "acronym_project", 99, 198, "SEARCH", {"acronym_project": "9ñ@!9ñ@!9ñ@!"}, "acronym_project_format_KO"],
    ["project", "id_sampling_methodology", 100, 199, "ADD", {"id_sampling_methodology": ""}, "id_sampling_methodology_min_size_KO"],
    ["project", "id_sampling_methodology", 100, 200, "ADD", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 101, 201, "ADD", {"id_sampling_methodology": "111111111111"}, "id_sampling_methodology_max_size_KO"],
    ["project", "id_sampling_methodology", 101, 202, "ADD", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 102, 203, "ADD", {"id_sampling_methodology": "abc"}, "id_sampling_methodology_format_KO"],
    ["project", "id_sampling_methodology", 102, 204, "ADD", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 103, 205, "ADD", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 103, 206, "ADD", {"id_sampling_methodology": ""}, "id_sampling_methodology_min_size_KO"],
    ["project", "id_sampling_methodology", 104, 207, "EDIT", {"id_sampling_methodology": ""}, "id_sampling_methodology_min_size_KO"],
    ["project", "id_sampling_methodology", 104, 208, "EDIT", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 105, 209, "EDIT", {"id_sampling_methodology": "111111111111"}, "id_sampling_methodology_max_size_KO"],
    ["project", "id_sampling_methodology", 105, 210, "EDIT", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 106, 211, "EDIT", {"id_sampling_methodology": "abc"}, "id_sampling_methodology_format_KO"],
    ["project", "id_sampling_methodology", 106, 212, "EDIT", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 107, 213, "EDIT", {"id_sampling_methodology": "7"}, true],
    ["project", "id_sampling_methodology", 107, 214, "EDIT", {"id_sampling_methodology": ""}, "id_sampling_methodology_min_size_KO"],
    ["project", "id_sampling_methodology", 108, 215, "SEARCH", {"id_sampling_methodology": "111111111111"}, "id_sampling_methodology_max_size_KO"],
    ["project", "id_sampling_methodology", 108, 216, "SEARCH", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 109, 217, "SEARCH", {"id_sampling_methodology": "abc"}, "id_sampling_methodology_format_KO"],
    ["project", "id_sampling_methodology", 109, 218, "SEARCH", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 110, 219, "SEARCH", {"id_sampling_methodology": "3"}, true],
    ["project", "id_sampling_methodology", 110, 220, "SEARCH", {"id_sampling_methodology": "abc"}, "id_sampling_methodology_format_KO"],
    ["project", "start_date_project", 111, 221, "ADD", {"start_date_project": "31/02/2024"}, "start_date_project_date_KO"],
    ["project", "start_date_project", 111, 222, "ADD", {"start_date_project": "15/01/2024"}, true],
    ["project", "start_date_project", 112, 223, "EDIT", {"start_date_project": "29/02/2023"}, "start_date_project_date_KO"],
    ["project", "start_date_project", 112, 224, "EDIT", {"start_date_project": "15/01/2024"}, true],
    ["project", "end_date_project", 113, 225, "ADD", {"end_date_project": "30/02/2024", "start_date_project": "01/01/2024"}, "end_date_project_date_KO"],
    ["project", "end_date_project", 113, 226, "ADD", {"end_date_project": "31/12/2025"}, true],
    ["project", "end_date_project", 114, 227, "EDIT", {"end_date_project": "31/04/2024", "start_date_project": "01/01/2024"}, "end_date_project_date_KO"],
    ["project", "end_date_project", 114, 228, "EDIT", {"end_date_project": "31/12/2025"}, true],

    // === Ampliacion caja negra: pruebas de valores limite, clases invalidas adicionales, MIME y calendario ===
    ["project", "id_project", 115, 229, "SEARCH", {"id_project": "12345678901"}, true],
    ["project", "id_project", 115, 230, "SEARCH", {"id_project": "123456789012"}, "id_project_max_size_KO"],
    ["project", "name_project", 116, 231, "ADD", {"name_project": "A".repeat(15)}, true],
    ["project", "name_project", 116, 232, "ADD", {"name_project": "A".repeat(14)}, "name_project_min_size_KO"],
    ["project", "name_project", 117, 233, "ADD", {"name_project": "A".repeat(100)}, true],
    ["project", "name_project", 117, 234, "ADD", {"name_project": "A".repeat(101)}, "name_project_max_size_KO"],
    ["project", "name_project", 118, 235, "ADD", {"name_project": "Nombre@Invalido!!"}, "name_project_format_KO"],
    ["project", "name_project", 118, 236, "ADD", {"name_project": "Valid Project Name For Tests"}, true],
    ["project", "responsable_project", 119, 237, "ADD", {"responsable_project": "A".repeat(6)}, true],
    ["project", "responsable_project", 119, 238, "ADD", {"responsable_project": "A".repeat(5)}, "responsable_project_min_size_KO"],
    ["project", "responsable_project", 120, 239, "ADD", {"responsable_project": "A".repeat(60)}, true],
    ["project", "responsable_project", 120, 240, "ADD", {"responsable_project": "A".repeat(61)}, "responsable_project_max_size_KO"],
    ["project", "responsable_project", 121, 241, "ADD", {"responsable_project": "Juan@123!!"}, "responsable_project_format_KO"],
    ["project", "responsable_project", 121, 242, "ADD", {"responsable_project": "Juan Garcia Lopez"}, true],
    ["project", "organization_project", 122, 243, "ADD", {"organization_project": "A".repeat(6)}, true],
    ["project", "organization_project", 122, 244, "ADD", {"organization_project": "A".repeat(5)}, "organization_project_min_size_KO"],
    ["project", "organization_project", 123, 245, "ADD", {"organization_project": "A".repeat(100)}, true],
    ["project", "organization_project", 123, 246, "ADD", {"organization_project": "A".repeat(101)}, "organization_project_max_size_KO"],
    ["project", "organization_project", 124, 247, "ADD", {"organization_project": "Org@2024!!"}, "organization_project_format_KO"],
    ["project", "organization_project", 124, 248, "ADD", {"organization_project": "Universidad de Vigo"}, true],
    ["project", "description_project", 125, 249, "ADD", {"description_project": "A".repeat(30)}, true],
    ["project", "description_project", 125, 250, "ADD", {"description_project": "A".repeat(29)}, "description_project_min_size_KO"],
    ["project", "description_project", 126, 251, "ADD", {"description_project": "A".repeat(500)}, true],
    ["project", "description_project", 126, 252, "ADD", {"description_project": "A".repeat(501)}, "description_project_max_size_KO"],
    ["project", "code_project", 127, 253, "ADD", {"code_project": "A".repeat(6)}, true],
    ["project", "code_project", 127, 254, "ADD", {"code_project": "A".repeat(5)}, "code_project_min_size_KO"],
    ["project", "code_project", 128, 255, "ADD", {"code_project": "A".repeat(50)}, true],
    ["project", "code_project", 128, 256, "ADD", {"code_project": "A".repeat(51)}, "code_project_max_size_KO"],
    ["project", "code_project", 129, 257, "ADD", {"code_project": "Codigo2024"}, "code_project_format_KO"],
    ["project", "code_project", 129, 258, "ADD", {"code_project": "Codigo Proyecto"}, true],
    ["project", "acronym_project", 130, 259, "ADD", {"acronym_project": "A".repeat(6)}, true],
    ["project", "acronym_project", 130, 260, "ADD", {"acronym_project": "A".repeat(5)}, "acronym_project_min_size_KO"],
    ["project", "acronym_project", 131, 261, "ADD", {"acronym_project": "A".repeat(15)}, true],
    ["project", "acronym_project", 131, 262, "ADD", {"acronym_project": "A".repeat(16)}, "acronym_project_max_size_KO"],
    ["project", "id_sampling_methodology", 132, 263, "ADD", {"id_sampling_methodology": "5"}, true],
    ["project", "id_sampling_methodology", 132, 264, "ADD", {"id_sampling_methodology": ""}, "id_sampling_methodology_min_size_KO"],
    ["project", "id_sampling_methodology", 133, 265, "ADD", {"id_sampling_methodology": "12345678901"}, true],
    ["project", "id_sampling_methodology", 133, 266, "ADD", {"id_sampling_methodology": "123456789012"}, "id_sampling_methodology_max_size_KO"],
    ["project", "file_project", 134, 267, "ADD", {"file_project": {"name": "documento.doc", "type": "application/msword", "size": 50000}}, true],
    ["project", "file_project", 134, 268, "ADD", {"file_project": {"name": "imagen.jpeg", "type": "image/jpeg", "size": 50000}}, "file_project_type_file_KO"],
    ["project", "file_project", 135, 269, "ADD", {"file_project": {"name": "documento.docx", "type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "size": 50000}}, true],
    ["project", "file_project", 135, 270, "ADD", {"file_project": {"name": "texto.txt", "type": "text/plain", "size": 50000}}, "file_project_type_file_KO"],
    ["project", "file_project", 136, 271, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 1999999}}, true],
    ["project", "file_project", 136, 272, "ADD", {"file_project": {"name": "proyecto.pdf", "type": "application/pdf", "size": 2000000}}, "file_project_max_size_file_KO"],
    ["project", "file_project", 137, 273, "ADD", {"file_project": {"name": "abc.pdf", "type": "application/pdf", "size": 1000}}, true],
    ["project", "file_project", 137, 274, "ADD", {"file_project": {"name": "ab.pdf", "type": "application/pdf", "size": 1000}}, "file_project_min_size_KO"],
    ["project", "file_project", 138, 275, "ADD", {"file_project": {"name": "a".repeat(96) + ".pdf", "type": "application/pdf", "size": 1000}}, true],
    ["project", "file_project", 138, 276, "ADD", {"file_project": {"name": "a".repeat(97) + ".pdf", "type": "application/pdf", "size": 1000}}, "file_project_max_size_KO"],
    ["project", "end_date_project", 139, 277, "ADD", {"start_date_project": "01/01/2024", "end_date_project": "29/02/2024"}, true],
    ["project", "end_date_project", 139, 278, "ADD", {"start_date_project": "01/01/2023", "end_date_project": "29/02/2023"}, "end_date_project_date_KO"]
];
